### ISSUE TITLE
New API error 442 after upgrade

### ISSUE THREAD

**Issue by alambel** [wallee-payment/magento-2#17]
Since the update to 1.3.15 yesterday evening, we receive the following issue from the API for most of our customers.

Error 442 connecting to the API  https://app-wallee.com/api/transaction/update?spaceId=XXXXX

message":"The line item discount must have the same sign as the line item amount."
"type":"DEVELOPER_ERROR"

Is there something we can do on our end to fix this issue?

**Comment by norgeindian** [comment]
@alambel , have a look at https://github.com/wallee-payment/magento-2/issues/16. 
It's the same issue, and Wallee currently works on a fix.

**Comment by theodorspringwallee** [comment]
Dear [alambel](https://github.com/alambel)

Thanks [norgeindian](https://github.com/norgeindian), yes we are working on this.

I assume, in this specific error message it's pointing out, that the subtrahend is slightly higher than the minuend, because of rounding issues, what ends in a negative result. We will check this.

Best regards

**Comment by theodorspringwallee** [comment]
Dear [norgeindian](https://github.com/norgeindian), [alambel](https://github.com/alambel)

This should be fixed now in 1.3.16: https://github.com/wallee-payment/magento-2/releases

Best regards
