### ISSUE TITLE
In-Store-Pickup orders stay in wrong status for pending invoices, if custom processing status is set

### ISSUE THREAD

**Issue by norgeindian** [wallee-payment/magento-2#30]
To reproduce this issue, please do the following steps:

- Create an order with in-store-pickup and pay it via wallee invoice
- The order will be created, is `processing` after a while, and the invoice is still `pending`
- Now change the status manually to some other status in the state `processing`
- Notify the customer, that the order is ready for pickup
- For you, the order is now more or less handled, the only thing, which remains, is the status change of the invoice 
- When this comes after some days, the status is still the same custom processing status you set, although the order is now complete.

As far as I see that, there are two reasons for that:

1. The webhook, which sets the invoice to be paid, only works with the status `shipped_wallee`
2. `\Wallee\Payment\Plugin\Sales\Model\ResourceModel\Order\Handler\State::aroundCheck` only sets the status `shipped_wallee`, if the status before was the default status of state `processing`

As it is Magento Core functionality to set a different custom status for a specific state, it would be awesome if this would not break the whole functionality of the status process in this case.

We use:

- Magento 2.4.5-p3 Enterprise Edition
- Wallee Module version 1.3.21
- PHP 8.1

**Comment by theodorspringwallee** [comment]
Dear [norgeindian](https://github.com/norgeindian)

I just did some reproductions to check how the current behaviour is, based on the "ISR PostFinance - QR-Invoice" method (ISR-Invoice).

Please let me know if I forgot something here, regarding your manual.

1. I did a MOTO transaction in the M2 backend.
2. M2 order status is then "HOLD DELIVERY" (and "FULFILL" on the wallee portal)
![grafik](https://github.com/wallee-payment/magento-2/assets/85299706/34e2edc0-f859-4ec8-a1b6-39f5713e313d)

![Bildschirmfoto 2023-07-27 um 10 58 47](https://github.com/wallee-payment/magento-2/assets/85299706/1c6b9c7c-5774-4c67-a011-91fd9c164f43)
3. And the invoice is then on "pending"
![Bildschirmfoto 2023-07-27 um 10 58 33](https://github.com/wallee-payment/magento-2/assets/85299706/403df6bc-bec7-4ec9-b040-b98aaa0365ce)
4. After marked the invoice (simulate the ISR paid process) in the wallee portal as paid, the invoice was properly updated in Magento:
![Bildschirmfoto 2023-07-27 um 11 00 33](https://github.com/wallee-payment/magento-2/assets/85299706/9242a5af-a592-4fce-9616-054c0a613a63)
![Bildschirmfoto 2023-07-27 um 11 00 55](https://github.com/wallee-payment/magento-2/assets/85299706/f1312709-c393-4436-a581-8446a2ebdc87)

That is the standard behaviour, provided in our test systems.

That are the states/keys on that our plugin is based: 
![grafik](https://github.com/wallee-payment/magento-2/assets/85299706/0c0eda25-f15b-4e8c-a37f-7fac9f9da83a)

Can you tell us, what all is different on your status definition?

Please, can you also update to the wallee 2.0.5 version, because we also had some changes regarding the status logic.

Thanks for your answer.

Best regards

**Comment by norgeindian** [comment]
@theodorspringwallee, in your process I don't really see where you changed the status of the order in Magento manually and where you notified the customer, that the order is ready for pickup.
Can you show me that again, please?

In general, please add another custom status under the state `processing` and switch to it, before you mark the invoice as paid.
You will see, that the order is not completed then, but still in your custom status.

**Comment by theodorspringwallee** [comment]
Dear [norgeindian](https://github.com/norgeindian)

In case of ISR-Invoices you don't need to manually fulfill the invoices. Respectively, the M2 order will be informed by the portal (when it received the payment). Because I didn't make a real payment, I manually initialized the payment of the customer via the portal (by mark the invoice as paid):
![grafik](https://github.com/wallee-payment/magento-2/assets/85299706/bb4a0b4a-e1ef-4d83-bf8c-f0210411ccce)

So I did no manual change on the Magento backend.

Can you provide us a reproduction video (including your status setup)?

Thanks for your answer.

Best regards

**Comment by norgeindian** [comment]
@theodorspringwallee , I tried to reproduce the issue on our Dev system to send you a video. But unfortunately it does not happen there, but only on live.
Sp let's close that issue for the time being and I will open it again, if I can reproduce it properly.
